### ISSUE TITLE
Add team section

### ISSUE THREAD

**Issue by Twissi** [OpenTechSchool/websitenext#25]
Design:
<img width="816" alt="Screenshot 2020-01-12 at 20 12 59" src="https://user-images.githubusercontent.com/261567/72224210-0ab1e600-3578-11ea-814a-933d75f261b8.png">

**Comment by gsambrotta** [comment]
we should think if we still want this section at all. 
Sometime ago we removed form the current site. Not sure exactly why

**Comment by Twissi** [comment]
I definitely like to have the chapter organizers listed on the chapter page similar to how it is on the current site.

**Comment by gsambrotta** [comment]
I also think the org. names on the chapter pages is a relevant information. People like to contact people directly. 
The reason why we removed this section in the old website, is: we, ots, don't use discourse/forum so much and, if i'm not wrong, discourse collect org names based on how active they are in the forum, which in result we often had, as first contact person, organizers that are not involved anymore in ots activities. 

I also like the idea to keep the org names in the `my_chapter.md` file, so each chapter is in full charge of their own page and if want t modify/improve has to change just one file. 
But is also true that those files get easily out of date... 

Anyway, i think for now we can simply copy what we have and in a second moment think about a better solution for this.

**Comment by gsambrotta** [comment]
@xMartin opened a WIP about this and ask me to take over since he has no time to work on it.
@Twissi since you assign this issue to you, do you wanna take it over? i'm also happy to do it, if you don't want/can't

**Comment by Twissi** [comment]
@gsambrotta will start looking at this now
