### ISSUE TITLE
Add chapter header

### ISSUE THREAD

**Issue by Twissi** [OpenTechSchool/websitenext#26]
Example design:
<img width="752" alt="Screenshot 2020-01-12 at 20 13 48" src="https://user-images.githubusercontent.com/261567/72224224-3a60ee00-3578-11ea-8799-1dfb10b6335c.png">

**Comment by gsambrotta** [comment]
done here https://github.com/OpenTechSchool/websitenext/commit/5981a06f7d04424eb43bdfe3643eb66ccdc33b98
