### ISSUE TITLE
Homepage Layout: keep or remove?

### ISSUE THREAD

**Issue by gsambrotta** [OpenTechSchool/websitenext#30]
I was wondering if we need a `<HomepageLayout />` component at all. 
My idea was to put all the style in the different Layout component so we can easily reuse.
But i now realize that we are not going to reuse the home page layout anywhere 😅 
So probably we can use `PageLayout` and just pass the usual general info.

Or does anyone see a reason why they could substantially differ at one point?

**Comment by Twissi** [comment]
I am fine with removing it for now. If we see a way to reusable layout styles in the future we can add it back in
