### ISSUE TITLE
Add "Inactive Chapter" section to Start a new chapter page

### ISSUE THREAD

**Issue by gsambrotta** [OpenTechSchool/websitenext#43]
people that want to start a new chapter might come from a city where we used to have a chapter, but now is inactive.
Add a list of inactive chapter in the "start a new chapter page" so people can get in contact with older organizer easily.

**Comment by Twissi** [comment]
Maybe here: https://websitenext.now.sh/en/guides#start-chapter

**Comment by Twissi** [comment]
Also, there is a bug that on the home page it also shows active chapters.

**Comment by Twissi** [comment]
@nycuma

**Comment by nycuma** [comment]
@Twissi I confirmed your invitation. Can you assign the issue to me now?!

**Comment by gsambrotta** [comment]
@Twissi  you mean that on the homepage shows INACTIVE chapter? 
Or you actually meant active?

Homepage chapter section is not done, my open PR #41  will  also fix the chapters list on homepage, so no worry about that :)

**Comment by Twissi** [comment]
@gsambrotta thank you!

**Comment by nycuma** [comment]
I'll wait until the PR #41 is merged.

**Comment by Twissi** [comment]
@nycuma #41 is merged 👯

**Comment by Twissi** [comment]
Done! Thanks @nycuma
