### ISSUE TITLE
Add pictures for active chapter and review content/social links

### ISSUE THREAD

**Issue by gsambrotta** [OpenTechSchool/websitenext#49]
~~@aoloe @zoepage would be great if you can take care of your team page. 
(Ola i know you are not in Dortmund anymore but maybe you are still in contact with some of the people there?)
You can see detail instruction how to do it in the README. 
And of course feel free to ask me if something is not clear.~~

~~@xMartin @bastianalbers @mamhoff anybody else:
Does anyone of you know how to tag here the people form Hamburg/Romagna/Brussel/Bristol/~~

Get in contact with people from each active chapter to ask them to fill in their chapter.md page with their content, social and team member.

How to: 
https://github.com/OpenTechSchool/websitenext#cities-data

**Comment by aoloe** [comment]
i will ask the regular participants of the co-learning, who wants to be on the list...

for the time being, you can add myself as the one in charge for the co-learning in zurich.

**Comment by gsambrotta** [comment]
UPDATE: i'm in contact with people from other chapters to ask for help for update their team page

**Comment by Twissi** [comment]
Update: Zürich is done!

**Comment by gsambrotta** [comment]
done https://github.com/OpenTechSchool/websitenext/pull/108
