### ISSUE TITLE
"Get in touch" section

### ISSUE THREAD

**Issue by gsambrotta** [OpenTechSchool/websitenext#70]
![Screen Shot 2020-03-18 at 19 16 47](https://user-images.githubusercontent.com/1055531/76994450-ae3fbe00-694e-11ea-8cc8-9f16210fe3af.png)

We need a slightly better copy.
The idea is to point people that want to contact us to the right media for contacting us.
We still want to focus as in-person kind of event so we want mostly people to show up to some event. 
Therefore as first we recommend them to join some event.
**Here we link to the community page**
Only we want first push for a more broad way of communicate so the chance that someone can answer soon are higher. **Our Slack**

At least we also want to leave a more direct and personal way of contacting, email. 
We anyway put it as last, in order to filter some requests.
The email address is: info@opentechschool.org

TODO:
- write a better copy following the order: "show up in person", "slack", "email"
- "show up in person" -> must have a link to "community" page
- "slack" -> link to our slack
- "email" -> info@opentechschool.org

**Comment by Twissi** [comment]
Maybe can also look into https://github.com/OpenTechSchool/websitenext/issues/57
