### ISSUE TITLE
Design Update: Contribute page

### ISSUE THREAD

**Issue by gsambrotta** [OpenTechSchool/websitenext#75]
In contribute page we have the "Volunteer" that is a bit bare. 
Let's think about a better design to be more catchy. 
maybe some illustration or icons.
Or maybe they don't even have to stay 3 point all in the same row.

Also, "Volunteer" should be the more prominent section. Not "Sponsor". Find a design solution also for this.

![Screen Shot 2020-03-18 at 19 46 04](https://user-images.githubusercontent.com/1055531/76996076-24452480-6951-11ea-8419-4c92db2b6e5b.png)

**Comment by Twissi** [comment]
Is updated in https://github.com/OpenTechSchool/websitenext/pull/94
