### ISSUE TITLE
Remove translation component (for now)

### ISSUE THREAD

**Issue by gsambrotta** [OpenTechSchool/websitenext#90]
We don't have all the translation ready yet so for now we just want all the website in english

**Comment by Twissi** [comment]
I think @mamhoff was volunteering to add translations. But I am fine to also remove for now

**Comment by gsambrotta** [comment]
Yep but i don't see so much activity yet so i would just hide it and show again when translation PR is merged

**Comment by gsambrotta** [comment]
PR #97
