### ISSUE TITLE
Update copyright in the footer

### ISSUE THREAD

**Issue by akarsh** [OpenTechSchool/websitenext#92]
- [ ] Change the year from 2020 to 2012-2020 in the copyright footer.

Since OTS was started from April 2012. We should have the copyright from 2012 - 2020. Instead of having only 2020.

- [ ] Add the word "Copyright" in front of the copyright symbol

- [ ] Use only single pipe "|" instead of "||" to separate the three hyperlinks in the footer menu

~~- [ ] Add hovering underline or highlight to the three hyperlinks in order to signify the user that upon clicking the link "Contact Us" they will be directed to a new page from the current page.~~

**Comment by gsambrotta** [comment]
Hey @akarsh thanks for checking the website and give some suggestions!

About the hovering, there is another issue to add hover to all the links. Once that would be done, it will automatically apply to footer links as well. To avoid duplicate code, could you please remove it from your check list? 

Why would you like to put the word "Copyright" in front of the copyright symbol? I think the symbol is pretty self explanatory

**Comment by akarsh** [comment]
@gsambrotta 

> About the hovering, there is another issue to add hover to all the links. Once that would be done, it will automatically apply to footer links as well. To avoid duplicate code, could you please remove it from your check list?

Okay I strike through it in the checklist

**Comment by akarsh** [comment]
> Why would you like to put the word "Copyright" in front of the copyright symbol? I think the symbol is pretty self explanatory

So when I put the checklist for copyright word i was mainly reading the use of the copyright word from [Google copyright usage for open source projects](https://opensource.google/docs/copyright/) 

Now I saw from [Mozilla footer developer documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer) that they use the symbol instead of writing the word.

But if you look at[ w3c documentation for footer](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-footer-element.html) they use copyright in front of the symbol.

**Comment by Twissi** [comment]
Thanks @akarsh ! Updated the year, but I think we don't need the copyright word.
Since the footer changed we don't need to change the pipes anymore. :)
