### ISSUE TITLE
Readme update: City 

### ISSUE THREAD

**Issue by gsambrotta** [OpenTechSchool/websitenext#93]
@xMartin or @Twissi could one of you add to this section of the readme https://github.com/OpenTechSchool/websitenext#cities-data
some explanation of how the member section works in each chapter page?
If i understood correctly we still grab member from discourse or from the city.md file.

I think would be very helpful for chapters organizers to know how to populate their own members section. Thank you!! 💟

**Comment by Twissi** [comment]
@xMartin added a PR. Not sure if we need more information about how to add a team to discourse. I haven't done it before.
